grafana:
  enabled: false  # We deploy Grafana separately

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

defaultRules:
  create: true
